name: Test suite

on: [pull_request]


jobs:
  tests:
    name: PHP ${{ matrix.php }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0 ]
        os: [ ubuntu-latest ]
        phpunit-versions: [ 'latest' ]
        include:
          - os: [ ubuntu-latest ]
            php: 8.1
            composer-flag: "--ignore-platform-reqs"

          - os: [ ubuntu-latest ]
            php: 7.3
            composer-flag: "--prefer-lowest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --prefer-dist ${{ matrix.composer-flag }}
      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo "::add-path::${HOME}/.symfony/bin"

      - name: PHPUnit tests
        run: ./vendor/bin/phpunit

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: nopassword
          MYSQL_DATABASE: outbox_messages
          MYSQL_USER: username
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306"
